default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['RAILS_DB_HOST'] %>
  port: <%= ENV['RAILS_DB_PORT'] %>
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  database: <%= ENV['RAILS_DB_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
